name: RSS Güncelleme
on:
  schedule:
    - cron: '0 0,1,2,34,5,6,9,12,15,18,21 * * *' # Günde 8 kez UTC
  workflow_dispatch: # Manuel çalıştırma için
permissions:
  contents: write # Repository içeriğine yazma izni ekleyin
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Token ekleyin
      - name: Python Kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Bağımlılıkları Yükle
        run: pip install -r requirements.txt
      - name: RSS Scriptini Çalıştır
        run: python rss_generator.py
      - name: Git'i Yapılandır
        run: |
          git config --local user.email "ebartan@gmail.com"
          git config --local user.name "ebartan"
      - name: RSS Beslemesini Commit et
        run: |
          git add ytu_haberler.xml
          git commit -m "RSS beslemesi güncellendi" || echo "Değişiklik yok"
          git push || echo "Push için değişiklik yok veya hata yok"
